### ISSUE TITLE
Add ccache

### ISSUE THREAD

**Issue by virtuald** [robotpy/build-actions#10]
There's a caching mechanism for github actions, this is probably doable? Not sure how much time it'll actually save though.

**Comment by auscompgeek** [comment]
I reckon for our larger packages (e.g. wpimath) it'd be worth it.

I'll note that we're severely limited by our Mac build parallelism - we get max 5 concurrent Mac builds before they're queued, and a single package fills that up.

`ccache` doesn't support MSVC though, and our Windows builds tend to take the longest. Could be worth looking into whether `sccache` can do the job, although I haven't used it.

**Comment by virtuald** [comment]
`ccache` has B-level MSVC support now, and is allegedly used by LibreOffice devs, so it probably works?

**Comment by auscompgeek** [comment]
Done in

- 0275b8ea1b9fbef32beecc7d05c8ef532278f26e
- 8b60ac1c94971e0554afc879b694c1a887f9136a
