### ISSUE TITLE
Consider sccache's GitHub Actions support

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/build-actions#15]
https://github.com/Mozilla-Actions/sccache-action

https://github.com/mozilla/sccache/blob/main/docs/GHA.md

Since it stores individual entries in the cache store directly we might get more cache hits and sharing between jobs? Would need some testing I think.

**Comment by virtuald** [comment]
The sccache artifacts are way larger, and I didn't really like it. Caching probably still needs to be addressed though.
